### ISSUE TITLE
set repo docs files

### ISSUE THREAD

**Issue by warengonzaga** [web3phl/homepage#2]
## Todo

- [x] add a readme file
- [x] add contributing file
- [x] add security policy file
- [x] add code of conduct file

**Comment by warengonzaga** [comment]
Merged!
